const adjectives = [
  'vintage',
  'upcycled',
  'secondhand',
  'artisinal',
  'handmade',
  'eco-friendly',
  'biodegradable',
  'custom',
  'personalized',
  'fair trade',
  'sustainable',
  'antique',
  'vegan',
  'thrifted',
  'locally sourced',
  'single origin',
  'unisex',
  'alternative',
];
