const things = [
  'wallets',
  'scissors',
  'handbags',
  'nosehair trimmers',
  'monocles',
  'succulents',
  'tarot cards',
  'dog leashes',
  'mattresses',
  'baby shoes',
  'unicycles',
  'postcards',
  'bath tissue',
  'hand towels',
  'hand lotions',
  'punch rugs',
  'enamel pins',
  'kitchen knives',
  'candles',
  'bath mats',
  'yoga mats',
  'sandals',
  'knitwear',
  'massage oil',
  'lampshades',
  'cast iron pans',
  'incense',
  'wreaths',
  'loofahs',
  'toothbrushes',
  'rocking chairs',
  'razors',
  'playing cards',
  'roller skates',
  'wallpaper',
  'footwear',
  'lint rollers',
  'wall calendars',
  'coffee mugs',
  'pocket watches',
  'tchotchkes',
  'journals',
  'streetwear',
  'turntables',
  'embroidery',
  'cutlery',
  'wigs',
  'cigar boxes',
  'tinctures',
  'sneakers',
  'buttons',
  'belts',
];
